### ISSUE TITLE
how to get raw scanrecord data of ble advertisement

### ISSUE THREAD

**Issue by francisraj** [Polidea/FlutterBleLib#31]
hi,
i'm trying to use flutter blelib package to develop an app (android and ios), i can not take advertisement data (rawdata scanrecord byte[] ).
=> how to get all value of raw data?,
=> and is it possible to take raw data both android and ios?,

could you please help me..,

**Comment by pawelByszewski** [comment]
@francisraj It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November
