### ISSUE TITLE
Maintaining a clean connection

### ISSUE THREAD

**Issue by mistertennistik** [Polidea/FlutterBleLib#41]
I have a problem to maintain a clean connection with a Bluetooth module (ESP32-S). I use the scan example of the library and modify it a little to connect and seems to do the job. But when I use MaterialPageRoute to switch to my app the connection sometimes crashes ..
What is the good way to maintain this connection between the differents Page of my app ?

**Comment by pawelByszewski** [comment]
@mistertennistik It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November
