### ISSUE TITLE
manufacturerData is empty when BLE packet is a Beacon

### ISSUE THREAD

**Issue by isaiahtaylor** [Polidea/FlutterBleLib#470]
Hello,

When scanning a BLE device that has the Beacon metadata (adding an Apple-specific ID to the manufacturer data followed by a proximity UUID), I get a scan result, but everything is nulled out. There is no manufacturerData.

**Comment by mikolak** [comment]
iOS treats iBeacon differently AFAIK (CoreLocation instead of CoreBluetooth). 

There are dedicated libraries for working with beacons:
https://pub.dev/packages/flutter_beacon
https://pub.dev/packages/beacons

I don't know them and haven't used them, so I can't really recommend anything to you. Might be be worth giving it a shot though.

Does the issue occur on Android as well?

**Comment by isaiahtaylor** [comment]
@mikolak you are correct, on more research it appears that iOS sanitizes packets that have iBeacon bits in them.
