### ISSUE TITLE
iOS monitor characteristics not implemented

### ISSUE THREAD

**Issue by JamesMcIntosh** [Polidea/FlutterBleLib#49]
I have implemented a fix for this in a fork

https://github.com/JamesMcIntosh/FlutterBleLib/commit/72e8ae5f68bd79156c6c0214f8559382beade920

**Comment by pawelByszewski** [comment]
@JamesMcIntosh It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November
