### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by votruk** [Polidea/FlutterBleLib#50]
Any updates of when you are planning to continue to support this library?

Btw I'm a huge fan of your android lib and it's very frustrating to see that you cannot use your library on flutter.

**Comment by passos** [comment]
looking for flutter update +1

**Comment by pawelByszewski** [comment]
@votruk @passos It has been a long time since we stopped maintaining the library but now we come with great news! We are currently working with Frontside on a new BLE Flutter library and BLE simulator. Beta version has been released already and we are going to release 2.0.0 in the first half of November

**Comment by votruk** [comment]
Such great news! I was already looking after your progress and documentation for some time. You do a great job, thank you!

**Comment by pawelByszewski** [comment]
Thank you @votruk, if you are going to use the lib then please take a look at BLE Simulator (https://github.com/Polidea/blemulator_flutter)

**Comment by passos** [comment]
cool~ that's really a great news. Thanks
